#!/bin/bash
set -e

mkdir -p build/run
cd build/run
rm vocaio -rf
unzip ../distributions/vocaio.zip
cd vocaio/bin
./vocaio jal.voca.lang.io.ExcelReaderMainKt ../../../../Duo-G.xlsx ../../../../../vocaquiz/src/main/resources/jal/voca/lang/
